// <auto-generated />
using System;
using Kuestencode.Beetwerk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kuestencode.Beetwerk.Data.Migrations
{
    [DbContext(typeof(BeetwerkDbContext))]
    [Migration("20261006080217_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.Garden", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoundaryGeoJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Zoom")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.GardenObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeometryGeoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeometryKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlantSpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("ParentObjectId");

                    b.HasIndex("PlantSpeciesId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.GardenTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GeneratedFromTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeometryGeoJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("NotifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Notify")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonEndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SeriesStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Status", "DueDate");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.NeighborRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeciesAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesBId");

                    b.HasIndex("SpeciesAId", "SpeciesBId")
                        .IsUnique();

                    b.ToTable("NeighborRelations", t =>
                        {
                            t.HasCheckConstraint("CK_NeighborRelations_Order", "\"SpeciesAId\" < \"SpeciesBId\"");
                        });
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowedGeometries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ObjectTypes");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.PlantSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlantSpecies");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.GardenObject", b =>
                {
                    b.HasOne("Kuestencode.Beetwerk.Domain.Entities.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kuestencode.Beetwerk.Domain.Entities.GardenObject", "ParentObject")
                        .WithMany()
                        .HasForeignKey("ParentObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Kuestencode.Beetwerk.Domain.Entities.PlantSpecies", "PlantSpecies")
                        .WithMany()
                        .HasForeignKey("PlantSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ObjectType");

                    b.Navigation("ParentObject");

                    b.Navigation("PlantSpecies");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.GardenTask", b =>
                {
                    b.HasOne("Kuestencode.Beetwerk.Domain.Entities.GardenObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Object");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.NeighborRelation", b =>
                {
                    b.HasOne("Kuestencode.Beetwerk.Domain.Entities.PlantSpecies", "SpeciesA")
                        .WithMany()
                        .HasForeignKey("SpeciesAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kuestencode.Beetwerk.Domain.Entities.PlantSpecies", "SpeciesB")
                        .WithMany()
                        .HasForeignKey("SpeciesBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpeciesA");

                    b.Navigation("SpeciesB");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("Kuestencode.Beetwerk.Domain.Entities.User", "User")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kuestencode.Beetwerk.Domain.Entities.User", b =>
                {
                    b.Navigation("PushSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
